# makefile

html:
	mkhowto --html --a4 tex/cgkit.tex

pdf:
	mkhowto --pdf --a4 tex/cgkit.tex
	mv cgkit.pdf cgkit-a4.pdf

pdf_letter:
	mkhowto --pdf --letter tex/cgkit.tex
	mv cgkit.pdf cgkit-letter.pdf
